checkpoint:
  best_checkpoint_metric: accuracy
  maximize_best_checkpoint_metric: true
  no_save: false
  restore_file: ???
  save_dir: ???
common:
  log_format: simple
  log_interval: 50
  seed: 0
  tensorboard_logdir: ???
criterion:
  _name: lra_cross_entropy
dataset:
  batch_size: 128
lr_scheduler:
  _name: inverse_sqrt
  warmup_updates: 4000
model:
  _name: transformer_lra_cifar10
  activation_dropout: 0.0
  activation_fn: silu
  attention_dropout: 0.1
  classifier_out_dim: 128
  dropout: 0.1
  encoder:
    attention_heads: 2
    embed_dim: 64
    ffn_embed_dim: 128
    layers: 2
    normalize_before: true
    xformers_att_config: '{''name'': ''favor'', ''dim_features'':256, ''input_features'':32, ''iter_before_redraw'':1500, ''device'':''cuda''}'
  input_type: image
  layer_type: transformer
  max_positions: 1024
  norm_type: layernorm
  sen_rep_type: mp
optimization:
  clip_norm: 1
  lr:
  - 0.0006
  max_epoch: 10000
  max_update: 100000
  sentence_avg: true
optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1.0e-09
  weight_decay: 0.1
task:
  _name: lra-image
  data: /dccstor/broccoli/LRA/cifar10
  num_classes: 10
  pixel_normalization: '[0.48, 0.24]'
